# Generated by Django 4.1.5 on 2023-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('operation_airlines', models.CharField(max_length=15)),
                ('departure_city', models.CharField(max_length=30)),
                ('arrival_city', models.CharField(max_length=30)),
                ('date_of_departure', models.DateField()),
                ('etd', models.TimeField()),
            ],
        ),
    ]
